http:
  addr: ":8080"
  cors:
    allow_origins:
      - "http://localhost:5173"
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "OPTIONS"
    allow_headers:
      - "Accept"
      - "Authorization"
      - "Content-Type"
    expose_headers: []
    allow_credentials: true
    max_age: 600

user_service:
  address: "user-service:50051"

movie_service:
  address: "movie-service:50053"

movie_list_service:
  address: "movie-list-service:50051"

review_service:
  address: "review-service:50054"
