# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from movie.v1 import movie_pb2 as movie_dot_v1_dot_movie__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in movie/v1/movie_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MovieServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMovies = channel.unary_unary(
                '/movie.v1.MovieService/GetMovies',
                request_serializer=movie_dot_v1_dot_movie__pb2.GetMoviesRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.GetMoviesResponse.FromString,
                _registered_method=True)
        self.GetPlaylistsForUser = channel.unary_unary(
                '/movie.v1.MovieService/GetPlaylistsForUser',
                request_serializer=movie_dot_v1_dot_movie__pb2.GetPlaylistsForUserRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.GetPlaylistsForUserResponse.FromString,
                _registered_method=True)
        self.CreatePlaylist = channel.unary_unary(
                '/movie.v1.MovieService/CreatePlaylist',
                request_serializer=movie_dot_v1_dot_movie__pb2.CreatePlaylistRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.CreatePlaylistResponse.FromString,
                _registered_method=True)
        self.RenamePlaylist = channel.unary_unary(
                '/movie.v1.MovieService/RenamePlaylist',
                request_serializer=movie_dot_v1_dot_movie__pb2.RenamePlaylistRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.RenamePlaylistResponse.FromString,
                _registered_method=True)
        self.DeletePlaylist = channel.unary_unary(
                '/movie.v1.MovieService/DeletePlaylist',
                request_serializer=movie_dot_v1_dot_movie__pb2.DeletePlaylistRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.DeletePlaylistResponse.FromString,
                _registered_method=True)
        self.AddMovieToPlaylist = channel.unary_unary(
                '/movie.v1.MovieService/AddMovieToPlaylist',
                request_serializer=movie_dot_v1_dot_movie__pb2.AddMovieToPlaylistRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.AddMovieToPlaylistResponse.FromString,
                _registered_method=True)
        self.RemoveMovieFromPlaylist = channel.unary_unary(
                '/movie.v1.MovieService/RemoveMovieFromPlaylist',
                request_serializer=movie_dot_v1_dot_movie__pb2.RemoveMovieFromPlaylistRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.RemoveMovieFromPlaylistResponse.FromString,
                _registered_method=True)
        self.CreateMovie = channel.unary_unary(
                '/movie.v1.MovieService/CreateMovie',
                request_serializer=movie_dot_v1_dot_movie__pb2.CreateMovieRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.CreateMovieResponse.FromString,
                _registered_method=True)
        self.UpdateMovie = channel.unary_unary(
                '/movie.v1.MovieService/UpdateMovie',
                request_serializer=movie_dot_v1_dot_movie__pb2.UpdateMovieRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.UpdateMovieResponse.FromString,
                _registered_method=True)
        self.DeleteMovie = channel.unary_unary(
                '/movie.v1.MovieService/DeleteMovie',
                request_serializer=movie_dot_v1_dot_movie__pb2.DeleteMovieRequest.SerializeToString,
                response_deserializer=movie_dot_v1_dot_movie__pb2.DeleteMovieResponse.FromString,
                _registered_method=True)


class MovieServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMovies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistsForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenamePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMovieToPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMovieFromPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMovies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovies,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.GetMoviesRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.GetMoviesResponse.SerializeToString,
            ),
            'GetPlaylistsForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistsForUser,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.GetPlaylistsForUserRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.GetPlaylistsForUserResponse.SerializeToString,
            ),
            'CreatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaylist,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.CreatePlaylistRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.CreatePlaylistResponse.SerializeToString,
            ),
            'RenamePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.RenamePlaylist,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.RenamePlaylistRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.RenamePlaylistResponse.SerializeToString,
            ),
            'DeletePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaylist,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.DeletePlaylistRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.DeletePlaylistResponse.SerializeToString,
            ),
            'AddMovieToPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMovieToPlaylist,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.AddMovieToPlaylistRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.AddMovieToPlaylistResponse.SerializeToString,
            ),
            'RemoveMovieFromPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMovieFromPlaylist,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.RemoveMovieFromPlaylistRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.RemoveMovieFromPlaylistResponse.SerializeToString,
            ),
            'CreateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMovie,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.CreateMovieRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.CreateMovieResponse.SerializeToString,
            ),
            'UpdateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMovie,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.UpdateMovieRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.UpdateMovieResponse.SerializeToString,
            ),
            'DeleteMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMovie,
                    request_deserializer=movie_dot_v1_dot_movie__pb2.DeleteMovieRequest.FromString,
                    response_serializer=movie_dot_v1_dot_movie__pb2.DeleteMovieResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movie.v1.MovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movie.v1.MovieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MovieService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMovies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/GetMovies',
            movie_dot_v1_dot_movie__pb2.GetMoviesRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.GetMoviesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistsForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/GetPlaylistsForUser',
            movie_dot_v1_dot_movie__pb2.GetPlaylistsForUserRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.GetPlaylistsForUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/CreatePlaylist',
            movie_dot_v1_dot_movie__pb2.CreatePlaylistRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.CreatePlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenamePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/RenamePlaylist',
            movie_dot_v1_dot_movie__pb2.RenamePlaylistRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.RenamePlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/DeletePlaylist',
            movie_dot_v1_dot_movie__pb2.DeletePlaylistRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.DeletePlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMovieToPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/AddMovieToPlaylist',
            movie_dot_v1_dot_movie__pb2.AddMovieToPlaylistRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.AddMovieToPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMovieFromPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/RemoveMovieFromPlaylist',
            movie_dot_v1_dot_movie__pb2.RemoveMovieFromPlaylistRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.RemoveMovieFromPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/CreateMovie',
            movie_dot_v1_dot_movie__pb2.CreateMovieRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.CreateMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/UpdateMovie',
            movie_dot_v1_dot_movie__pb2.UpdateMovieRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.UpdateMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.v1.MovieService/DeleteMovie',
            movie_dot_v1_dot_movie__pb2.DeleteMovieRequest.SerializeToString,
            movie_dot_v1_dot_movie__pb2.DeleteMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
