syntax = "proto3";
package review;

service ReviewService {
  rpc GetReviews (GetReviewsRequest) returns (ReviewsResponse);
  rpc AddReview (AddReviewRequest) returns (ReviewResponse);
}

message GetReviewsRequest { string movie_id = 1; }

message AddReviewRequest {
  string movie_id = 1;
  string user_id = 2;
  string text = 3;
}

message ReviewResponse {
  string id = 1;
  string movie_id = 2;
  string user_id = 3;
  string username = 4;
  string text = 5;
  string created_at = 6;
}

message ReviewsResponse { repeated ReviewResponse items = 1; }