# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from movielist.v1 import movielist_pb2 as movielist_dot_v1_dot_movielist__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in movielist/v1/movielist_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MovieListServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FilterMoviesByPlaylist = channel.unary_unary(
                '/movielist.v1.MovieListService/FilterMoviesByPlaylist',
                request_serializer=movielist_dot_v1_dot_movielist__pb2.FilterMoviesByPlaylistRequest.SerializeToString,
                response_deserializer=movielist_dot_v1_dot_movielist__pb2.FilterMoviesByPlaylistResponse.FromString,
                _registered_method=True)
        self.GetPlaylistsForMovie = channel.unary_unary(
                '/movielist.v1.MovieListService/GetPlaylistsForMovie',
                request_serializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForMovieRequest.SerializeToString,
                response_deserializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForMovieResponse.FromString,
                _registered_method=True)
        self.GetPlaylistsForUser = channel.unary_unary(
                '/movielist.v1.MovieListService/GetPlaylistsForUser',
                request_serializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForUserRequest.SerializeToString,
                response_deserializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForUserResponse.FromString,
                _registered_method=True)
        self.CreatePlaylist = channel.unary_unary(
                '/movielist.v1.MovieListService/CreatePlaylist',
                request_serializer=movielist_dot_v1_dot_movielist__pb2.CreatePlaylistRequest.SerializeToString,
                response_deserializer=movielist_dot_v1_dot_movielist__pb2.CreatePlaylistResponse.FromString,
                _registered_method=True)
        self.RenamePlaylist = channel.unary_unary(
                '/movielist.v1.MovieListService/RenamePlaylist',
                request_serializer=movielist_dot_v1_dot_movielist__pb2.RenamePlaylistRequest.SerializeToString,
                response_deserializer=movielist_dot_v1_dot_movielist__pb2.RenamePlaylistResponse.FromString,
                _registered_method=True)
        self.DeletePlaylist = channel.unary_unary(
                '/movielist.v1.MovieListService/DeletePlaylist',
                request_serializer=movielist_dot_v1_dot_movielist__pb2.DeletePlaylistRequest.SerializeToString,
                response_deserializer=movielist_dot_v1_dot_movielist__pb2.DeletePlaylistResponse.FromString,
                _registered_method=True)
        self.AddMovieToPlaylist = channel.unary_unary(
                '/movielist.v1.MovieListService/AddMovieToPlaylist',
                request_serializer=movielist_dot_v1_dot_movielist__pb2.AddMovieToPlaylistRequest.SerializeToString,
                response_deserializer=movielist_dot_v1_dot_movielist__pb2.AddMovieToPlaylistResponse.FromString,
                _registered_method=True)
        self.RemoveMovieFromPlaylist = channel.unary_unary(
                '/movielist.v1.MovieListService/RemoveMovieFromPlaylist',
                request_serializer=movielist_dot_v1_dot_movielist__pb2.RemoveMovieFromPlaylistRequest.SerializeToString,
                response_deserializer=movielist_dot_v1_dot_movielist__pb2.RemoveMovieFromPlaylistResponse.FromString,
                _registered_method=True)
        self.GetPlaylistMovies = channel.unary_unary(
                '/movielist.v1.MovieListService/GetPlaylistMovies',
                request_serializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistMoviesRequest.SerializeToString,
                response_deserializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistMoviesResponse.FromString,
                _registered_method=True)


class MovieListServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FilterMoviesByPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistsForMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistsForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenamePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMovieToPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveMovieFromPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlaylistMovies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieListServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FilterMoviesByPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.FilterMoviesByPlaylist,
                    request_deserializer=movielist_dot_v1_dot_movielist__pb2.FilterMoviesByPlaylistRequest.FromString,
                    response_serializer=movielist_dot_v1_dot_movielist__pb2.FilterMoviesByPlaylistResponse.SerializeToString,
            ),
            'GetPlaylistsForMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistsForMovie,
                    request_deserializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForMovieRequest.FromString,
                    response_serializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForMovieResponse.SerializeToString,
            ),
            'GetPlaylistsForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistsForUser,
                    request_deserializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForUserRequest.FromString,
                    response_serializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForUserResponse.SerializeToString,
            ),
            'CreatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaylist,
                    request_deserializer=movielist_dot_v1_dot_movielist__pb2.CreatePlaylistRequest.FromString,
                    response_serializer=movielist_dot_v1_dot_movielist__pb2.CreatePlaylistResponse.SerializeToString,
            ),
            'RenamePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.RenamePlaylist,
                    request_deserializer=movielist_dot_v1_dot_movielist__pb2.RenamePlaylistRequest.FromString,
                    response_serializer=movielist_dot_v1_dot_movielist__pb2.RenamePlaylistResponse.SerializeToString,
            ),
            'DeletePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaylist,
                    request_deserializer=movielist_dot_v1_dot_movielist__pb2.DeletePlaylistRequest.FromString,
                    response_serializer=movielist_dot_v1_dot_movielist__pb2.DeletePlaylistResponse.SerializeToString,
            ),
            'AddMovieToPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMovieToPlaylist,
                    request_deserializer=movielist_dot_v1_dot_movielist__pb2.AddMovieToPlaylistRequest.FromString,
                    response_serializer=movielist_dot_v1_dot_movielist__pb2.AddMovieToPlaylistResponse.SerializeToString,
            ),
            'RemoveMovieFromPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveMovieFromPlaylist,
                    request_deserializer=movielist_dot_v1_dot_movielist__pb2.RemoveMovieFromPlaylistRequest.FromString,
                    response_serializer=movielist_dot_v1_dot_movielist__pb2.RemoveMovieFromPlaylistResponse.SerializeToString,
            ),
            'GetPlaylistMovies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlaylistMovies,
                    request_deserializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistMoviesRequest.FromString,
                    response_serializer=movielist_dot_v1_dot_movielist__pb2.GetPlaylistMoviesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movielist.v1.MovieListService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movielist.v1.MovieListService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MovieListService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FilterMoviesByPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movielist.v1.MovieListService/FilterMoviesByPlaylist',
            movielist_dot_v1_dot_movielist__pb2.FilterMoviesByPlaylistRequest.SerializeToString,
            movielist_dot_v1_dot_movielist__pb2.FilterMoviesByPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistsForMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movielist.v1.MovieListService/GetPlaylistsForMovie',
            movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForMovieRequest.SerializeToString,
            movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistsForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movielist.v1.MovieListService/GetPlaylistsForUser',
            movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForUserRequest.SerializeToString,
            movielist_dot_v1_dot_movielist__pb2.GetPlaylistsForUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movielist.v1.MovieListService/CreatePlaylist',
            movielist_dot_v1_dot_movielist__pb2.CreatePlaylistRequest.SerializeToString,
            movielist_dot_v1_dot_movielist__pb2.CreatePlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenamePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movielist.v1.MovieListService/RenamePlaylist',
            movielist_dot_v1_dot_movielist__pb2.RenamePlaylistRequest.SerializeToString,
            movielist_dot_v1_dot_movielist__pb2.RenamePlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movielist.v1.MovieListService/DeletePlaylist',
            movielist_dot_v1_dot_movielist__pb2.DeletePlaylistRequest.SerializeToString,
            movielist_dot_v1_dot_movielist__pb2.DeletePlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMovieToPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movielist.v1.MovieListService/AddMovieToPlaylist',
            movielist_dot_v1_dot_movielist__pb2.AddMovieToPlaylistRequest.SerializeToString,
            movielist_dot_v1_dot_movielist__pb2.AddMovieToPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveMovieFromPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movielist.v1.MovieListService/RemoveMovieFromPlaylist',
            movielist_dot_v1_dot_movielist__pb2.RemoveMovieFromPlaylistRequest.SerializeToString,
            movielist_dot_v1_dot_movielist__pb2.RemoveMovieFromPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlaylistMovies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movielist.v1.MovieListService/GetPlaylistMovies',
            movielist_dot_v1_dot_movielist__pb2.GetPlaylistMoviesRequest.SerializeToString,
            movielist_dot_v1_dot_movielist__pb2.GetPlaylistMoviesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
