syntax = "proto3";

package user.v1;

option go_package = "user-service/gen/go/user;user";

service UserService {
    rpc Register(RegisterRequest) returns (RegisterResponse);
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc Refresh(RefreshRequest) returns (RefreshResponse);
    rpc GetUsersByIDs(GetUsersByIDsRequest) returns (GetUsersByIDsResponse);
}

enum Role {
    ROLE_UNSPECIFIFED = 0;
    ROLE_ADMIN = 1;
}

message User {
    int64 id = 1;
    string username = 2;
    string email = 3;
    string password_hash = 4;
    string bio = 5;
    string avatar_url = 6;
    string status = 7;
    Role role = 8;
}

message Tokens {
    string access_token = 1;
    string refresh_token = 2;
}

message RegisterRequest {
    string username = 1;
    string password = 2;
    string email = 3;
}

message RegisterResponse {
    User user = 1;
    Tokens tokens = 2;
}

message LoginRequest {
    string username = 1;
    string password = 2;
}

message LoginResponse {
    User user = 1;
    Tokens tokens = 2;
}

message RefreshRequest {
    string refresh_token = 1;
}

message RefreshResponse {
    Tokens tokens = 1;
}

message GetUsersByIDsRequest {
    repeated int64 ids = 1;
    repeated string usernames = 2;
    int32 limit = 3;
    int32 offset = 4;
}

message GetUsersByIDsResponse {
    repeated User users = 1;
}