# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: review/v1/review.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'review/v1/review.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16review/v1/review.proto\x12\treview.v1\"%\n\x11GetReviewsRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\t\"2\n\x10\x41\x64\x64ReviewRequest\x12\x10\n\x08movie_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"k\n\x06Review\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08movie_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"6\n\x12GetReviewsResponse\x12 \n\x05items\x18\x01 \x03(\x0b\x32\x11.review.v1.Review\"6\n\x11\x41\x64\x64ReviewResponse\x12!\n\x06review\x18\x01 \x01(\x0b\x32\x11.review.v1.Review2\xa2\x01\n\rReviewService\x12I\n\nGetReviews\x12\x1c.review.v1.GetReviewsRequest\x1a\x1d.review.v1.GetReviewsResponse\x12\x46\n\tAddReview\x12\x1b.review.v1.AddReviewRequest\x1a\x1c.review.v1.AddReviewResponseB%Z#review-service/gen/go/review;reviewb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'review.v1.review_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#review-service/gen/go/review;review'
  _globals['_GETREVIEWSREQUEST']._serialized_start=37
  _globals['_GETREVIEWSREQUEST']._serialized_end=74
  _globals['_ADDREVIEWREQUEST']._serialized_start=76
  _globals['_ADDREVIEWREQUEST']._serialized_end=126
  _globals['_REVIEW']._serialized_start=128
  _globals['_REVIEW']._serialized_end=235
  _globals['_GETREVIEWSRESPONSE']._serialized_start=237
  _globals['_GETREVIEWSRESPONSE']._serialized_end=291
  _globals['_ADDREVIEWRESPONSE']._serialized_start=293
  _globals['_ADDREVIEWRESPONSE']._serialized_end=347
  _globals['_REVIEWSERVICE']._serialized_start=350
  _globals['_REVIEWSERVICE']._serialized_end=512
# @@protoc_insertion_point(module_scope)
