# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from review.v1 import review_pb2 as review_dot_v1_dot_review__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in review/v1/review_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReviewServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReviews = channel.unary_unary(
                '/review.v1.ReviewService/GetReviews',
                request_serializer=review_dot_v1_dot_review__pb2.GetReviewsRequest.SerializeToString,
                response_deserializer=review_dot_v1_dot_review__pb2.GetReviewsResponse.FromString,
                _registered_method=True)
        self.AddReview = channel.unary_unary(
                '/review.v1.ReviewService/AddReview',
                request_serializer=review_dot_v1_dot_review__pb2.AddReviewRequest.SerializeToString,
                response_deserializer=review_dot_v1_dot_review__pb2.AddReviewResponse.FromString,
                _registered_method=True)


class ReviewServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReviews,
                    request_deserializer=review_dot_v1_dot_review__pb2.GetReviewsRequest.FromString,
                    response_serializer=review_dot_v1_dot_review__pb2.GetReviewsResponse.SerializeToString,
            ),
            'AddReview': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReview,
                    request_deserializer=review_dot_v1_dot_review__pb2.AddReviewRequest.FromString,
                    response_serializer=review_dot_v1_dot_review__pb2.AddReviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'review.v1.ReviewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('review.v1.ReviewService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReviewService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/review.v1.ReviewService/GetReviews',
            review_dot_v1_dot_review__pb2.GetReviewsRequest.SerializeToString,
            review_dot_v1_dot_review__pb2.GetReviewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/review.v1.ReviewService/AddReview',
            review_dot_v1_dot_review__pb2.AddReviewRequest.SerializeToString,
            review_dot_v1_dot_review__pb2.AddReviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
