syntax = "proto3";

package movie.v1;

option go_package = "movie-service/gen/go/movie;movie";

service MovieService {
  rpc GetMovies(GetMoviesRequest) returns (GetMoviesResponse);
  rpc CreateMovie(CreateMovieRequest) returns (CreateMovieResponse);
  rpc UpdateMovie(UpdateMovieRequest) returns (UpdateMovieResponse);
  rpc DeleteMovie(DeleteMovieRequest) returns (DeleteMovieResponse);
  rpc MovieExists(MovieExistsRequest) returns (MovieExistsResponse);
}

message GetMoviesRequest {
  int32 limit = 1;
  int32 offset = 2;
  optional string search_query = 3;
  optional string genre = 4;
  repeated string ids = 5;
  optional string playlist_id = 6;
  string user_id = 7;
  bool enrich_playlists = 8;
}

message GetMoviesResponse {
  repeated MovieDetailed items = 1;
  int32 total = 2;
  string poster = 3;
}

message MovieDetailed {
  string id = 1;
  string title = 2;
  string description = 3;
  int32 release_year = 4;
  repeated string genres = 5;
  string poster = 6;
  repeated PlaylistInfo playlists = 7;
}

message PlaylistInfo {
  string id = 1;
  string name = 2;
}

message CreateMovieRequest {
  string title = 1;
  string description = 2;
  int32 release_year = 3;
  repeated string genres = 4;
  string poster = 5;
}

message CreateMovieResponse {
  Movie movie = 1;
}

message UpdateMovieRequest {
  string id = 1;
  optional string title = 2;
  optional string description = 3;
  optional int32 release_year = 4;
  repeated string genres = 5;
  string poster = 6;
}

message UpdateMovieResponse {
  Movie movie = 1;
}

message DeleteMovieRequest {
  string id = 1;
}

message DeleteMovieResponse {}

message Movie {
  string id = 1;
  string title = 2;
  string description = 3;
  int32 release_year = 4;
  repeated string genres = 5;
  string poster = 6;
}

message MovieExistsRequest {
  string id = 1;
}

message MovieExistsResponse {
  bool exists = 1;
}
